//autogenerated:yes
//nolint:revive,misspell,govet,lll
package danny
// Every done send this to GCS every second.
type MessageDroneStatus struct {
    // command type
    CommandType MAV_COMMAND_TYPE `mavenum:"uint8"`
    // drone id
    DroneId int16
    // leading latitude
    LeadingLat int32
    // leading longtitude
    LeadingLon int32
    // rtk fix
    RtkFix uint8
    // sat count
    RtkSatCount uint8
    // tow
    RtkTow int32
    // drone latitude
    RtkLat int32
    // drone longtitude
    RtkLon int32
    // drone altitude
    RtkAlt float32
    // drone heading
    RtkHeading float32
    // current drone battery
    Battery uint8
    // is drone arm
    Arm uint8
    // current drone mode
    Mode uint8
    // is drone landed
    Land uint8
}

// GetID implements the message.Message interface.
func (*MessageDroneStatus) GetID() uint32 {
    return 12921
}
